DeathClear: false
ItemProbability: 10.0
LocProbability: 0.5
Misdiagnosis: 80.0
BotanyFool:
- 'POTION'
- 'APPLE'
- 'CARROT'
- 'POTATO'
DirtyFool:
- 'ROTTEN_FLESH'
- 'SPIDER_EYE'
RawFool:
- 'PORKCHOP'
- 'BEEF'
- 'CHICKEN'
- 'PUFFERFISH'
- 'SILVERFISH'
- 'TROPICAL_FISH'
- 'RAW_FISH'
- 'LEGACY_RAW_FISH'
Entity:
- 'WOLF'
- 'OCELOT'
OceanBiomes:
- 'OCEAN'
- 'COLD_OCEAN'
- 'DEEP_COLD_OCEAN'
- 'DEEP_FROZEN_OCEAN'
- 'DEEP_LUKEWARM_OCEAN'
- 'DEEP_OCEAN'
- 'DEEP_WARM_OCEAN'
- 'FROZEN_OCEAN'
- 'LUKEWARM_OCEAN'
- 'WARM_OCEAN'
DampBiomes:
- 'BEACH'
- 'DESERT_LAKES'
- 'SAVANNA'
- 'SAVANNA_PLATEAU'
- 'SHATTERED_SAVANNA_PLATEAU'
- 'SHATTERED_SAVANNA'
- 'JUNGLE'
- 'JUNGLE_EDGE'
- 'JUNGLE_HILLS'
- 'SWAMP'
- 'SWAMP_HILLS'
Water:
- 'WATER'
- 'STATIONARY_WATER'
- 'WATER_LILY'
- 'LEGACY_WATER_LILY'
- 'LEGACY_STATIONARY_WATER'
- 'LEGACY_WATER'